### ISSUE TITLE
Quick Jar scan

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/scancode-toolkit#218]
I received this suggestion: being able to quickly scans Java Jars, focusing on the META-INF directory and packages and not on the whole content for a quick scan could be very useful and this without requiring a full archive extraction

**Comment by mjherzog** [comment]
Wouldn't this be a packagecode scan for Jar metadata rather than scancode?

**Comment by pombredanne** [comment]
well yes and no. packagedcode is just a module of scancode, so this would likely be a scan with code  effectively in the packagedcode module from scancode.

**Comment by dmlangdon** [comment]
I appreciate your willingness to look at this. Not sure of the implementation details, but personally I think this should be built into scancode an not a separate option. Doesn't sound like it would be, but this seems like a logical extension of the tool functionality.

**Comment by pombredanne** [comment]
@dmlangdon this would not be a separate option, but built in a standard scancode scan.

**Comment by pombredanne** [comment]
@dmlangdon The reference to `packagedcode` is about which Python package the corresponding code would live in.

**Comment by pombredanne** [comment]
This is now done in ScanCode toolkit and we can also match JARS in matchcode. Closing
