### ISSUE TITLE
ScanCode not showing license embedded in jar

### ISSUE THREAD

**Issue by akintayo** [aboutcode-org/scancode-toolkit#244]
I downloaded the toolkit and ran the sample application. I checked the html page and saw it listed all the licenses in the package. I however observed that there are license files in the directory. For example under the JGroups, there's the EULA and license text files which the scan code reports on.

For my application where there's no explicit EULA or license text file in the package I don;t see anything in the report after running the scan code even though the third party jar i depend on has the license embedded in there jar package (usually in the META-INF directory)

**Comment by pombredanne** [comment]
@akintayo You need to run the `extractcode` command first on a copy of your code tree to extract the archives (including Jars) before running a scan. 
There is a plan to make these seamless though:
https://github.com/nexB/scancode-toolkit/issues/14

I hope this helps! Sorry if the doc is not explicit on this

**Comment by akintayo** [comment]
@pombredanne but what if im using maven to manage dependencies; what will happen? Will I need to do a mvn package to build and pull dependencies into the target directory from where i run the extracode and then scancode?

**Comment by pombredanne** [comment]
@akintayo yes: you will need to pull you dependencies, then run extractcode`  then `scancode`
Not perfect I reckon, but not hard either.
Ideally (and I have some code I need to push for Maven-specific pom parsing), the pull and extract would be part of a single scan operation. Though the pull is likely always best handled by Maven.

**Comment by pombredanne** [comment]
@akintayo I am keeping this ticket open so you can be alerted when we have the transparent archive extraction in place.

**Comment by akintayo** [comment]
ok. Thanks

**Comment by pombredanne** [comment]
This is now handled in ScanCode.io, and not here. We have comprehensive pipelines that can extract Jars, parse POMs and match that to the PurlDB. Closing this now at last.
