### ISSUE TITLE
ScanCode Toolkit Documentation for CI tools

### ISSUE THREAD

**Issue by pierrelapointe** [aboutcode-org/scancode-toolkit#254]
We need documentation on how to set up scans using Continuous Integration tools such as Jenkins or Travis.

See also https://github.com/nexB/scancode-toolkit/issues/210

**Comment by starlord1311** [comment]
i would like to take up this issue

**Comment by pombredanne** [comment]
sure!

**Comment by starlord1311** [comment]
can you tell what am i supposed to do?

**Comment by D-lang14** [comment]
Hey! @pierrelapointe , I would like to know about the issue and solve it. Can you assign me the issue the guide me through?

**Comment by D-lang14** [comment]
Can anyone guide me through this issue? I would like to contribute so that I can learn more about this.

**Comment by pombredanne** [comment]
This is closed in favor of the scancode.io issue at https://github.com/aboutcode-org/scancode.io/issues/619
