### ISSUE TITLE
GUI to run scancode-toolkit on windows and Linux

### ISSUE THREAD

**Issue by balusarakesh** [aboutcode-org/scancode-toolkit#268]
I think it's good to have a GUI for scancode-toolkit for both windows and Linux systems.
a sample mock up can be something like this : 
![scan_v1](https://cloud.githubusercontent.com/assets/17168699/15479697/41b33ec0-20d6-11e6-8f82-33d93f67564b.jpg)

**Comment by balusarakesh** [comment]
ticket entered in the wrong repo

**Comment by pombredanne** [comment]
Not sure what you mean by wrong repo. But this is quite a valid  input here .

**Comment by pombredanne** [comment]
To consider: https://github.com/chriskiehl/Gooey

**Comment by pombredanne** [comment]
We have a web gui now with scancode.io https://github.com/nexB/scancode.io/ and I do not think we want to have a GUI wrapper to the CLI. But I am leaving this open if someone wants to contribute

**Comment by pombredanne** [comment]
The CLI here and web combo in ScanCode.io are fine and we will not write a UI wrapper for the CLI for now. Closing!
