### ISSUE TITLE
test

### ISSUE THREAD

**Issue by invisiblepancake** [aboutcode-org/scancode-toolkit#3890]
### Description

> Please leave a brief description of the bug or feature request:

### How To Reproduce

> Tell us how to reproduce the issue. 

### System configuration

> For bug reports, it really helps us to know:

* What OS are you running on? (Windows/MacOS/Linux)
* What version of scancode-toolkit was used to generate the scan file?
* What installation method was used to install/run scancode? (pip/source download/other)

**Comment by swastkk** [comment]
@invisiblepancake What is this issue for?
